# Pacman configuration for AliveOS ISO builder
#

[options]
HoldPkg      = pacman glibc
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Use syslog
#UseSyslog
#Color
#NoProgressBar
# We cannot use check space in chroot
#CheckSpace
#VerbosePkgLists
ParallelDownloads = 8

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[xlibre]
Server = https://x11libre.net/repo/arch_based/x86_64
SigLevel = Never

[garuda]
Server = https://garuda.garudalinux.org/repo/garuda/x86_64
SigLevel = Never

[chaotic-aur]
Server = https://cdn-mirror.chaotic.cx/chaotic-aur/x86_64
SigLevel = Never

[aliveos-repo]
Server = https://twilight.github.io/aliveos-repo/x86_64
SigLevel = Never

